In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pycaret.regression import *

In [2]:
df = pd.read_csv('../data/gold.csv')
# Drop the variables from the dataframe
df = df.drop(['charles_river_dummy'], axis=1)

In [3]:
# Initialize setup
regression_setup = setup(data = df, target = 'median_home_value', session_id = 42)

# Compare models
best_model = compare_models()

# Print the best model
print(best_model)

ExtraTreesRegressor(n_jobs=-1, random_state=42)